# A singular matrix 😞

In [2]:
import os, sys
import numpy as np
import scipy.linalg    # A case where the top level package needs it's subpackages imported explicitly. 
sys.version

'3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]'

In [25]:
def is_full_rank(the_m, d):
    return np.linalg.matrix_rank(the_m) == d

def random_ar(d):
    return np.reshape( np.array(np.random.choice(range(d*d), d*d, replace=False)), (d,d))

def random_symmetric_ar(d):
    diagonal = np.random.choice(range(d*d), d, replace=False) 
    off_diagonal = list(np.random.choice(range(d*d), int(0.5 * d * (d-1)), replace=False) - round(d/2) )   # Yes the count is always an integer
    # Clever way to fill the matrix?  Iterate thru the off diagonal lower matrix and pop the off diagnozal elements
    ar = np.zeros((d,d))
    # Set the diagonal
    for k in range(d):
        ar[k,k]  = diagonal[k]
    for a_row in range(1,d):
        for a_col in range(a_row):
            ar[a_row, a_col] = off_diagonal.pop()
    return ar + ar.T

In [33]:
sym_ar = random_symmetric_ar(8)
print(np.linalg.matrix_rank(sym_ar))
sym_ar

8


array([[116.,  41.,  36.,   8.,  35.,  45.,  39.,  15.],
       [ 41.,  18.,  26.,  48.,  51.,  55.,  19.,  38.],
       [ 36.,  26.,  42.,  46.,  29.,  13.,  54.,  22.],
       [  8.,  48.,  46.,  34.,   1.,   2.,  47.,  31.],
       [ 35.,  51.,  29.,   1.,  98.,   7.,  50.,  -4.],
       [ 45.,  55.,  13.,   2.,   7.,  44.,   0.,  52.],
       [ 39.,  19.,  54.,  47.,  50.,   0.,  56.,  -2.],
       [ 15.,  38.,  22.,  31.,  -4.,  52.,  -2.,  68.]])

In [3]:
# Create a non-singular matrix. Any random arrangment of integers probably works. 
d = 3  # dimension 
an_array = random_ar(d)
is_full_rank(an_array, 3), an_array  #  Is this random matrix full rank? 

(True,
 array([[2, 5, 1],
        [8, 3, 7],
        [0, 4, 6]]))

In [4]:
# How often is the random matrix singular
fails = 0
for k in range(10000):
   f = 1 - is_full_rank(random_ar(d), d) 
   fails += f
fails/10000

0.0097

In [6]:
array_inv = np.linalg.inv(an_array)
array_inv

array([[ 0.04385965,  0.11403509, -0.14035088],
       [ 0.21052632, -0.05263158,  0.02631579],
       [-0.14035088,  0.03508772,  0.14912281]])

In [12]:
# Given it has an inverse , do they commute?
np.round(array_inv @ an_array),  np.round(an_array @ array_inv)  # Yes!! 

(array([[ 1.,  0.,  0.],
        [ 0.,  1., -0.],
        [ 0.,  0.,  1.]]),
 array([[ 1.,  0., -0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]]))

In [8]:
# Gassian elimination on a singular matrix
A = np.array([[3,2,4],[1,2,2], [1,0,1]])
b = np.transpose(np.array([[0,0,0]]))
A

array([[3, 2, 4],
       [1, 2, 2],
       [1, 0, 1]])

In [9]:
# The LU decomposition - Gaussian elimination
P, L, U = scipy.linalg.lu(A)

In [10]:
# View the Gassian elimination results for matrix A
P,L,np.round(U)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [ 0.33333333,  1.        ,  0.        ],
        [ 0.33333333, -0.5       ,  1.        ]]),
 array([[3., 2., 4.],
        [0., 1., 1.],
        [0., 0., 0.]]))

In [11]:
# The Gaussian elimination for A Transpose
P, L, U = scipy.linalg.lu(A.T)
P,L,np.round(U)

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [ 0.75, -0.5 ,  1.  ]]),
 array([[ 4.,  2.,  1.],
        [ 0.,  1., -0.],
        [ 0.,  0.,  0.]]))

In [34]:
# Factor a random symmetrix matrix. 
# The LU decomposition - Gaussian elimination
P, L, U = scipy.linalg.lu(sym_ar)
print(np.round(L))
print(np.round(U))
P

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0. -0.  1.  0.  0.  0.  0.]
 [ 0.  1.  0. -0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -0.  1.  0.  0.]
 [ 0.  0. -1.  0.  0. -0.  1.  0.]
 [ 0.  0. -0.  1. -0. -1. -0.  1.]]
[[116.  41.  36.   8.  35.  45.  39.  15.]
 [  0.  45.  44.  33.  -1.  -1.  44.  30.]
 [  0.   0. -39. -30.  -5.  27. -53.  20.]
 [  0.   0.   0.  35.  37.  46. -12.  36.]
 [  0.   0.   0.   0. 108.   1.  22. -29.]
 [  0.   0.   0.   0.   0.  15.  -9.  14.]
 [  0.   0.   0.   0.   0.   0. -16.   6.]
 [  0.   0.   0.   0.   0.   0.   0.  11.]]


array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.]])

In [30]:
L @ U

array([[36., 19.,  5., 16., 10.],
       [19., 24.,  8.,  9., 14.],
       [ 5.,  8., 26.,  2.,  1.],
       [16.,  9.,  2., 32.,  3.],
       [10., 14.,  1.,  3., 34.]])

In [6]:
# Another L - (See Strang exercise 1.5.3)
L1 = np.array([[1,0,0],[2,1,0], [0, 0, 1]])
L2 = np.array([[1,0,0],[0,1,0], [0, -1, 1]])
np.linalg.inv(L2@ L1), L2@ L1, L1 @ L2

(array([[ 1.,  0.,  0.],
        [-2.,  1., -0.],
        [ 0.,  1.,  1.]]),
 array([[ 1,  0,  0],
        [ 2,  1,  0],
        [-2, -1,  1]]),
 array([[ 1,  0,  0],
        [ 2,  1,  0],
        [ 0, -1,  1]]))