# A singular matrix 😞

In [1]:
import os, sys
import numpy as np
import scipy.linalg    # A case where the top level package needs it's subpackages imported explicitly. 
sys.version

'3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]'

In [24]:
A = np.array([[3,2,4],[1,2,2], [1,0,1]])
b = np.transpose(np.array([[0,0,0]]))
A

array([[3, 2, 4],
       [1, 2, 2],
       [1, 0, 1]])

In [19]:
P, L, U = scipy.linalg.lu(A)

In [20]:
P,L,np.round(U)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [ 0.33333333,  1.        ,  0.        ],
        [ 0.33333333, -0.5       ,  1.        ]]),
 array([[3., 2., 4.],
        [0., 1., 1.],
        [0., 0., 0.]]))

In [26]:
P, L, U = scipy.linalg.lu(A.T)
P,L,np.round(U)

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [ 0.75, -0.5 ,  1.  ]]),
 array([[ 4.,  2.,  1.],
        [ 0.,  1., -0.],
        [ 0.,  0.,  0.]]))