# A singular matrix 😞

In [1]:
import os, sys
import numpy as np
import scipy.linalg    # A case where the top level package needs it's subpackages imported explicitly. 
sys.version

'3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]'

In [25]:
def is_full_rank(the_m, d):
    return np.linalg.matrix_rank(the_m) == d

def random_ar(d):
    return np.reshape( np.array(np.random.choice(range(d*d), d*d, replace=False)), (d,d))

In [54]:
# Create a non-singular matrix. Any random arrangment of integers probably works. 
d = 3  # dimension 
an_array = random_ar(d)
is_full_rank(an_array, 3), an_array

(True,
 array([[4, 3, 6],
        [0, 5, 1],
        [8, 2, 7]]))

In [60]:
fails = 0
for k in range(10000):
   f = 1 - is_full_rank(random_ar(d), d) 
   fails += f
fails/10000

0.0095

In [55]:
array_inv = np.linalg.inv(an_array)
array_inv

array([[-0.39285714,  0.10714286,  0.32142857],
       [-0.0952381 ,  0.23809524,  0.04761905],
       [ 0.47619048, -0.19047619, -0.23809524]])

In [57]:
# Given it has an inverse , do they commute?
np.round(array_inv @ an_array),  an_array @ array_inv

(array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0., -0.,  1.]]),
 array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [ 1.11022302e-16,  0.00000000e+00,  1.00000000e+00]]))

In [2]:
A = np.array([[3,2,4],[1,2,2], [1,0,1]])
b = np.transpose(np.array([[0,0,0]]))
A

array([[3, 2, 4],
       [1, 2, 2],
       [1, 0, 1]])

In [3]:
P, L, U = scipy.linalg.lu(A)

In [4]:
P,L,np.round(U)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [ 0.33333333,  1.        ,  0.        ],
        [ 0.33333333, -0.5       ,  1.        ]]),
 array([[3., 2., 4.],
        [0., 1., 1.],
        [0., 0., 0.]]))

In [5]:
P, L, U = scipy.linalg.lu(A.T)
P,L,np.round(U)

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [ 0.75, -0.5 ,  1.  ]]),
 array([[ 4.,  2.,  1.],
        [ 0.,  1., -0.],
        [ 0.,  0.,  0.]]))

In [6]:
# Another L - (See Strang exercise 1.5.3)
L1 = np.array([[1,0,0],[2,1,0], [0, 0, 1]])
L2 = np.array([[1,0,0],[0,1,0], [0, -1, 1]])
np.linalg.inv(L2@ L1), L2@ L1, L1 @ L2

(array([[ 1.,  0.,  0.],
        [-2.,  1., -0.],
        [ 0.,  1.,  1.]]),
 array([[ 1,  0,  0],
        [ 2,  1,  0],
        [-2, -1,  1]]),
 array([[ 1,  0,  0],
        [ 2,  1,  0],
        [ 0, -1,  1]]))