# Solving Single Decisions

## The "Party Problem" example, Value of Information

__ A continuation of partyproblem_xdsl.ipynb__

JMA 17 Sept 2025

In [1]:
# Imports from the python standard library
import math, re, os, sys
from pathlib import Path
import itertools            # to flatten lists

# Import array and dataframe packages
import numpy as np
# import numpy.linalg as la
import pandas as pd

import networkx as nx

# for extract_net
# from ID_operations import * 
from potential_operations import *
import BN

## Bayes networks object

In [2]:
NETWORK_FILE = 'PartyProblem_asym.xdsl'
# BN structure is contained under the node branch
parsed = BN.extract_net(NETWORK_FILE)
nodes, extensions = parsed
# tags tell the node type. 
# [( k.get('id'), k.tag) for k in nodes]
# CPT contents are stored in row major order (first row, second row, ...)
# Parents are the first matrix dimension -- matrix is Row Markov
pp_net = BN.reap(parsed)
pp_net.pr_nodes()

found nodes
Edges:  [('Weather', 'Preferences'), ('Party_location', 'Preferences'), ('Weather', 'Detector'), ('Adjustor', 'Detector')] 

>>> Party_location <<<
Party_location: decision
	states: ['Outdoors', 'Porch', 'Indoors']
	named tensor: [('Party_location', 'm')], [3]
       [0, 0, 0]

>>> Weather <<<
Weather: cpt
	states: ['Sunshine', 'Rain']
	named tensor: [('Weather', 'm')], [2]
       [0.4000, 0.6000]

>>> Preferences <<<
Preferences: utility
	states: ['utility']
	named tensor: [('Weather', 'c'), ('Party_location', 'c'), ('Preferences', 'm')], [2, 3, 1]
       [[[100.],
         [ 90.],
         [ 40.]],

        [[  0.],
         [ 20.],
         [ 50.]]]

>>> Adjustor <<<
Adjustor: cpt
	states: ['absent', 'present']
	named tensor: [('Adjustor', 'm')], [2]
       [0.1000, 0.9000]

>>> Detector <<<
Detector: cpt
	states: ['SaySun', 'SayRain']
	named tensor: [('Weather', 'c'), ('Adjustor', 'c'), ('Detector', 'm')], [2, 2, 2]
       [[[0.5100, 0.4900],
         [0.8700, 0.1300]],

reap: Party_location, decision
reap: Weather, cpt
reap: Preferences, utility
reap: Utility, maux
Unsupported node type: maux
reap: Adjustor, cpt
reap: Detector, cpt


## Add the Weather variable as an information arc to the decision node

Modify the decision Potential to include a dimension for the Weather variable

### Solution order of node operations

- Add observation dimension to the Party_location decision
- Compute EV for each option, conditioned on weather state
- Maximize over options (conditioned on weather)
- Update Decn policy with maximum entries (0-1s)
- Expect out weather to get EV

In [2]:
# Add an additional dimension for a observational arc
# to  extend a decision policy table. 
decn_w_observation = condition_decision(
    pp_net.get_potential('Party_location'), 
    pp_net.get_potential('Weather'))
decn_w_observation

NameError: name 'condition_decision' is not defined

In [ ]:
squeezed_pref = pp_net.get_potential('Preferences').cpt.squeeze(-1)
squeezed_pref

tensor([[100.,  90.,  40.],
        [  0.,  20.,  50.]])

In [ ]:
sv,  six = squeezed_pref.max(dim=1)
sv, six

(tensor([100.,  50.]), tensor([0, 2]))

In [ ]:
v,  ix = pp_net.get_potential('Preferences').cpt.max(dim=1)
v, ix 

(tensor([[100.],
         [ 50.]]),
 tensor([[0],
         [2]]))

In [ ]:
# This is how multiple elements can be indexed 
v == pp_net.get_potential('Preferences').cpt[range(2), six]

tensor([[True],
        [True]])

In [ ]:
inx = pp_net.get_potential('Preferences').cpt.argmax(dim=1)
# This is how multiple elements can be indexed 
# THe first argument is the list of 1st dim coordinates
# The second argument 
decn_w_observation.cpt[range(2), list(inx)] = 1
decn_w_observation.pr_potential()

	named tensor: [('Weather', 'c'), ('Party_location', 'm')], [2, 3]
       [[1, 0, 0],
        [0, 0, 1]]


### Take expectation of decisions over weather

The expected value if the decision is made __after__ the weather is known

See Figure 12.6, p.252, Howard & Abbas


In [ ]:
# marginalize_utility() 
# TODO use potential_operations
max_decn = (pp_net.get_potential('Preferences').cpt.squeeze(2) * decn_w_observation.cpt).sum(1)
'EV with observation: ', (max_decn * pp_net.get_potential('Weather').cpt).sum().item()

('EV with observation: ', 70.0)

## Observe Detector of the Weather

Detector is a garbled version of the true weather, so it is not as valuable. 

- Flip the arc so that Detector -> Weather, by first joining the two. 
- Extract new  Detector marginal and the conditionings Weather | Detector
- Next remove Weather by expecting it into the utility

In [ ]:
# Flip Detector <- Weather arc
# Note this just returns both the Detector posterior and the Weather | Detector conditional
weather_p = pp_net.get_potential('Weather')
detector_p = pp_net.get_potential('Detector')
wd_joint = join(weather_p, detector_p)  #TODO wrap these in a reverse arc & remove function
weather_marginal = marginalize_out(wd_joint, 'Detector')
weather_marginal.pr_potential()